/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpRouteImport } from './routes/up'
import { Route as VexRouteImport } from './routes/vex'
import { Route as UpIndexRouteImport } from './routes/up/index'
import { Route as UpCartRouteImport } from './routes/up/cart'
import { Route as UpCheckoutRouteImport } from './routes/up/checkout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as UpProductSlugRouteImport } from './routes/up/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpRoute = UpRouteImport.update({
  id: '/up',
  path: '/up',
  getParentRoute: () => rootRouteImport,
} as any)
const VexRoute = VexRouteImport.update({
  id: '/vex',
  path: '/vex',
  getParentRoute: () => rootRouteImport,
} as any)
const UpIndexRoute = UpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UpRoute,
} as any)
const UpCartRoute = UpCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => UpRoute,
} as any)
const UpCheckoutRoute = UpCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => UpRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UpProductSlugRoute = UpProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => UpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/not-found': typeof NotFoundRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/up': typeof UpRouteWithChildren
  '/vex': typeof VexRoute
  '/up/cart': typeof UpCartRoute
  '/up/checkout': typeof UpCheckoutRoute
  '/up/': typeof UpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/up/product/$slug': typeof UpProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/not-found': typeof NotFoundRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/vex': typeof VexRoute
  '/up/cart': typeof UpCartRoute
  '/up/checkout': typeof UpCheckoutRoute
  '/up': typeof UpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/up/product/$slug': typeof UpProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/not-found': typeof NotFoundRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/up': typeof UpRouteWithChildren
  '/vex': typeof VexRoute
  '/up/cart': typeof UpCartRoute
  '/up/checkout': typeof UpCheckoutRoute
  '/up/': typeof UpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/up/product/$slug': typeof UpProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertise'
    | '/login'
    | '/maps'
    | '/not-found'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/up'
    | '/vex'
    | '/up/cart'
    | '/up/checkout'
    | '/up/'
    | '/api/auth/$'
    | '/up/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/login'
    | '/maps'
    | '/not-found'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/vex'
    | '/up/cart'
    | '/up/checkout'
    | '/up'
    | '/api/auth/$'
    | '/up/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertise'
    | '/login'
    | '/maps'
    | '/not-found'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/up'
    | '/vex'
    | '/up/cart'
    | '/up/checkout'
    | '/up/'
    | '/api/auth/$'
    | '/up/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertiseRoute: typeof AdvertiseRoute
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRoute
  NotFoundRoute: typeof NotFoundRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UpRoute: typeof UpRouteWithChildren
  VexRoute: typeof VexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up': {
      id: '/up'
      path: '/up'
      fullPath: '/up'
      preLoaderRoute: typeof UpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vex': {
      id: '/vex'
      path: '/vex'
      fullPath: '/vex'
      preLoaderRoute: typeof VexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up/': {
      id: '/up/'
      path: '/'
      fullPath: '/up/'
      preLoaderRoute: typeof UpIndexRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/cart': {
      id: '/up/cart'
      path: '/cart'
      fullPath: '/up/cart'
      preLoaderRoute: typeof UpCartRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/checkout': {
      id: '/up/checkout'
      path: '/checkout'
      fullPath: '/up/checkout'
      preLoaderRoute: typeof UpCheckoutRouteImport
      parentRoute: typeof UpRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up/product/$slug': {
      id: '/up/product/$slug'
      path: '/product/$slug'
      fullPath: '/up/product/$slug'
      preLoaderRoute: typeof UpProductSlugRouteImport
      parentRoute: typeof UpRoute
    }
  }
}

interface UpRouteChildren {
  UpCartRoute: typeof UpCartRoute
  UpCheckoutRoute: typeof UpCheckoutRoute
  UpIndexRoute: typeof UpIndexRoute
  UpProductSlugRoute: typeof UpProductSlugRoute
}

const UpRouteChildren: UpRouteChildren = {
  UpCartRoute: UpCartRoute,
  UpCheckoutRoute: UpCheckoutRoute,
  UpIndexRoute: UpIndexRoute,
  UpProductSlugRoute: UpProductSlugRoute,
}

const UpRouteWithChildren = UpRoute._addFileChildren(UpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertiseRoute: AdvertiseRoute,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  NotFoundRoute: NotFoundRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UpRoute: UpRouteWithChildren,
  VexRoute: VexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
