/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UpRouteImport } from './routes/up'
import { Route as UpIndexRouteImport } from './routes/up/index'
import { Route as UpAboutRouteImport } from './routes/up/about'
import { Route as UpAccountRouteImport } from './routes/up/account'
import { Route as UpCartRouteImport } from './routes/up/cart'
import { Route as UpCheckoutRouteImport } from './routes/up/checkout'
import { Route as UpContactRouteImport } from './routes/up/contact'
import { Route as UpFaqRouteImport } from './routes/up/faq'
import { Route as UpPrivacyRouteImport } from './routes/up/privacy'
import { Route as UpShippingRouteImport } from './routes/up/shipping'
import { Route as UpSizeGuideRouteImport } from './routes/up/size-guide'
import { Route as UpTermsRouteImport } from './routes/up/terms'
import { Route as UpThanksRouteImport } from './routes/up/thanks'
import { Route as UpTrackRouteImport } from './routes/up/track'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'
import { Route as UpProductSlugRouteImport } from './routes/up/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UpRoute = UpRouteImport.update({
  id: '/up',
  path: '/up',
  getParentRoute: () => rootRouteImport,
} as any)
const UpIndexRoute = UpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UpRoute,
} as any)
const UpAboutRoute = UpAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => UpRoute,
} as any)
const UpAccountRoute = UpAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => UpRoute,
} as any)
const UpCartRoute = UpCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => UpRoute,
} as any)
const UpCheckoutRoute = UpCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => UpRoute,
} as any)
const UpContactRoute = UpContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => UpRoute,
} as any)
const UpFaqRoute = UpFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => UpRoute,
} as any)
const UpPrivacyRoute = UpPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => UpRoute,
} as any)
const UpShippingRoute = UpShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => UpRoute,
} as any)
const UpSizeGuideRoute = UpSizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => UpRoute,
} as any)
const UpTermsRoute = UpTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => UpRoute,
} as any)
const UpThanksRoute = UpThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => UpRoute,
} as any)
const UpTrackRoute = UpTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => UpRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const UpProductSlugRoute = UpProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => UpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/up': typeof UpRouteWithChildren
  '/up/about': typeof UpAboutRoute
  '/up/account': typeof UpAccountRoute
  '/up/cart': typeof UpCartRoute
  '/up/checkout': typeof UpCheckoutRoute
  '/up/contact': typeof UpContactRoute
  '/up/faq': typeof UpFaqRoute
  '/up/privacy': typeof UpPrivacyRoute
  '/up/shipping': typeof UpShippingRoute
  '/up/size-guide': typeof UpSizeGuideRoute
  '/up/terms': typeof UpTermsRoute
  '/up/thanks': typeof UpThanksRoute
  '/up/track': typeof UpTrackRoute
  '/up/': typeof UpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/up/product/$slug': typeof UpProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/up/about': typeof UpAboutRoute
  '/up/account': typeof UpAccountRoute
  '/up/cart': typeof UpCartRoute
  '/up/checkout': typeof UpCheckoutRoute
  '/up/contact': typeof UpContactRoute
  '/up/faq': typeof UpFaqRoute
  '/up/privacy': typeof UpPrivacyRoute
  '/up/shipping': typeof UpShippingRoute
  '/up/size-guide': typeof UpSizeGuideRoute
  '/up/terms': typeof UpTermsRoute
  '/up/thanks': typeof UpThanksRoute
  '/up/track': typeof UpTrackRoute
  '/up': typeof UpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/up/product/$slug': typeof UpProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/up': typeof UpRouteWithChildren
  '/up/about': typeof UpAboutRoute
  '/up/account': typeof UpAccountRoute
  '/up/cart': typeof UpCartRoute
  '/up/checkout': typeof UpCheckoutRoute
  '/up/contact': typeof UpContactRoute
  '/up/faq': typeof UpFaqRoute
  '/up/privacy': typeof UpPrivacyRoute
  '/up/shipping': typeof UpShippingRoute
  '/up/size-guide': typeof UpSizeGuideRoute
  '/up/terms': typeof UpTermsRoute
  '/up/thanks': typeof UpThanksRoute
  '/up/track': typeof UpTrackRoute
  '/up/': typeof UpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/up/product/$slug': typeof UpProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/up'
    | '/up/about'
    | '/up/account'
    | '/up/cart'
    | '/up/checkout'
    | '/up/contact'
    | '/up/faq'
    | '/up/privacy'
    | '/up/shipping'
    | '/up/size-guide'
    | '/up/terms'
    | '/up/thanks'
    | '/up/track'
    | '/up/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/up/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/up/about'
    | '/up/account'
    | '/up/cart'
    | '/up/checkout'
    | '/up/contact'
    | '/up/faq'
    | '/up/privacy'
    | '/up/shipping'
    | '/up/size-guide'
    | '/up/terms'
    | '/up/thanks'
    | '/up/track'
    | '/up'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/up/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/up'
    | '/up/about'
    | '/up/account'
    | '/up/cart'
    | '/up/checkout'
    | '/up/contact'
    | '/up/faq'
    | '/up/privacy'
    | '/up/shipping'
    | '/up/size-guide'
    | '/up/terms'
    | '/up/thanks'
    | '/up/track'
    | '/up/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/up/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UpRoute: typeof UpRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up': {
      id: '/up'
      path: '/up'
      fullPath: '/up'
      preLoaderRoute: typeof UpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up/': {
      id: '/up/'
      path: '/'
      fullPath: '/up/'
      preLoaderRoute: typeof UpIndexRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/about': {
      id: '/up/about'
      path: '/about'
      fullPath: '/up/about'
      preLoaderRoute: typeof UpAboutRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/account': {
      id: '/up/account'
      path: '/account'
      fullPath: '/up/account'
      preLoaderRoute: typeof UpAccountRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/cart': {
      id: '/up/cart'
      path: '/cart'
      fullPath: '/up/cart'
      preLoaderRoute: typeof UpCartRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/checkout': {
      id: '/up/checkout'
      path: '/checkout'
      fullPath: '/up/checkout'
      preLoaderRoute: typeof UpCheckoutRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/contact': {
      id: '/up/contact'
      path: '/contact'
      fullPath: '/up/contact'
      preLoaderRoute: typeof UpContactRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/faq': {
      id: '/up/faq'
      path: '/faq'
      fullPath: '/up/faq'
      preLoaderRoute: typeof UpFaqRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/privacy': {
      id: '/up/privacy'
      path: '/privacy'
      fullPath: '/up/privacy'
      preLoaderRoute: typeof UpPrivacyRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/shipping': {
      id: '/up/shipping'
      path: '/shipping'
      fullPath: '/up/shipping'
      preLoaderRoute: typeof UpShippingRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/size-guide': {
      id: '/up/size-guide'
      path: '/size-guide'
      fullPath: '/up/size-guide'
      preLoaderRoute: typeof UpSizeGuideRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/terms': {
      id: '/up/terms'
      path: '/terms'
      fullPath: '/up/terms'
      preLoaderRoute: typeof UpTermsRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/thanks': {
      id: '/up/thanks'
      path: '/thanks'
      fullPath: '/up/thanks'
      preLoaderRoute: typeof UpThanksRouteImport
      parentRoute: typeof UpRoute
    }
    '/up/track': {
      id: '/up/track'
      path: '/track'
      fullPath: '/up/track'
      preLoaderRoute: typeof UpTrackRouteImport
      parentRoute: typeof UpRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up/product/$slug': {
      id: '/up/product/$slug'
      path: '/product/$slug'
      fullPath: '/up/product/$slug'
      preLoaderRoute: typeof UpProductSlugRouteImport
      parentRoute: typeof UpRoute
    }
  }
}

interface UpRouteChildren {
  UpAboutRoute: typeof UpAboutRoute
  UpAccountRoute: typeof UpAccountRoute
  UpCartRoute: typeof UpCartRoute
  UpCheckoutRoute: typeof UpCheckoutRoute
  UpContactRoute: typeof UpContactRoute
  UpFaqRoute: typeof UpFaqRoute
  UpPrivacyRoute: typeof UpPrivacyRoute
  UpShippingRoute: typeof UpShippingRoute
  UpSizeGuideRoute: typeof UpSizeGuideRoute
  UpTermsRoute: typeof UpTermsRoute
  UpThanksRoute: typeof UpThanksRoute
  UpTrackRoute: typeof UpTrackRoute
  UpIndexRoute: typeof UpIndexRoute
  UpProductSlugRoute: typeof UpProductSlugRoute
}

const UpRouteChildren: UpRouteChildren = {
  UpAboutRoute: UpAboutRoute,
  UpAccountRoute: UpAccountRoute,
  UpCartRoute: UpCartRoute,
  UpCheckoutRoute: UpCheckoutRoute,
  UpContactRoute: UpContactRoute,
  UpFaqRoute: UpFaqRoute,
  UpPrivacyRoute: UpPrivacyRoute,
  UpShippingRoute: UpShippingRoute,
  UpSizeGuideRoute: UpSizeGuideRoute,
  UpTermsRoute: UpTermsRoute,
  UpThanksRoute: UpThanksRoute,
  UpTrackRoute: UpTrackRoute,
  UpIndexRoute: UpIndexRoute,
  UpProductSlugRoute: UpProductSlugRoute,
}

const UpRouteWithChildren = UpRoute._addFileChildren(UpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UpRoute: UpRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
